---
title: "Basic_EDA"
author: "Aleksei Zverev"
date: "2023-06-02"
output: html_document
---

```{r setup, include=TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(fig.width = 14, fig.height = 8)
 

library('phyloseq')
library('tidyverse')
library('ggVennDiagram')


set.seed(5678)
setwd('~/Analysis/16s-amplicon-processing/')
ps <- readRDS("ps.RData")
ps
```

## Brief view on samples

```{r}
sample_sums(ps) %>% sort()
taxa_sums(ps) %>% log() %>%  hist()
ps@sam_data[1:8,]
```


## Plot barplots

```{r}
# Draw barplot of relative abundance by taxa level
bargraph <- function(ps, rank, threshold=0.05, percents=FALSE){
  require(dplyr)
  require(ggplot2)
  require(phyloseq)
  
  ps <- prune_taxa(taxa_sums(ps) > 0, ps)
  ps2 <- tax_glom(ps, taxrank = rank)
  ps3 = transform_sample_counts(ps2, function(x) x / sum(x) )
  data <- psmelt(ps3) # create dataframe from phyloseq object
  data$Plot <- as.character(data[,rank]) # convert to character
  data$Plot[data$Abundance < threshold] <- paste0("<", threshold, " abund.")
  medians <- data %>% group_by(Plot) %>% mutate(median=median(data$Abundance))
  remainder <- medians[medians$median <= threshold,]$Plot
  data$Percentage = ifelse(data$Plot != paste0("<", threshold, " abund."),
                           round(data$Abundance, 3)*100, NA)
  
  # create palette long enough for our data
  base.palette <- c("darkblue", "darkgoldenrod1", "darkseagreen", "darkorchid", "darkolivegreen1", "lightskyblue", 
                    "darkgreen", "deeppink", "khaki2", "firebrick", "brown1", "darkorange1", "cyan1", "royalblue4", 
                    "darksalmon", "dodgerblue3", "steelblue1", "darkgoldenrod1", "brown1", "cyan1", "darkgrey")
  required.colors <- nlevels(factor(data$Plot))
  repeats = required.colors %/% length(base.palette) + 1
  palette <- rep(base.palette, length.out = repeats * length(base.palette))
  
  ggplot(data=data, aes(x=Sample, y=Abundance, fill=Plot)) +
    geom_bar(stat="identity", position="stack") + 
    theme_light() +
    guides() +
    scale_fill_manual(values = palette) +
    scale_y_continuous(limits = c(0,1), 
                       expand = expansion(mult = c(.01, .01))) +
    ylab("Relative Abundance") +
    xlab("Samples") +
    theme(legend.position="bottom",
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank()) +
    if (percents) {
      geom_text(aes(label = Percentage),
                position = position_stack(vjust = 0.5), size = 1.5)
    }
}

bargraph(ps, "Phylum", 0.02) +
  facet_grid(cols = vars(Group, BioRepeat), scales = "free", space = "free")
# ggsave("bars.tiff", units="in", width=12, height=8, dpi=300, compression = 'lzw')
```

## Heatmap

```{r}
plot_heatmap <- function(ps, taxa = "Genus", log.transform = TRUE){
  require(dplyr)
  require(phyloseq)
  require(ggplot2)
  
  ps <- prune_taxa(taxa_sums(ps) > 0, ps)
  ps <- tax_glom(ps, taxa)
  sig.taxa.long <- psmelt(ps) %>%
    arrange(Phylum) %>% 
    mutate(row = row_number())
  
  sig.taxa.long$Abundance <- as.numeric(sig.taxa.long$Abundance)
  sig.taxa.long$Taxa <- sig.taxa.long[,taxa]
  
  sig.taxa.long[sig.taxa.long == "Burkholderia-Caballeronia-Paraburkholderia"] <- "Burkholderia"
  sig.taxa.long[sig.taxa.long == "Allorhizobium-Neorhizobium-Pararhizobium-Rhizobium"] <- "Pararhizobium"
  
  ggplot(sig.taxa.long, aes(x = SampleID, y = reorder(Taxa, row))) +
    {if(log.transform) geom_tile(aes(fill=log(Abundance)))} +
    {if(!log.transform) geom_tile(aes(fill=Abundance))} +
    scale_fill_distiller(palette = "OrRd", trans = "reverse") +
    facet_grid(rows = vars(Phylum), scales = "free", space = "free") +
    theme_light() +
    theme(strip.text.y = element_text(angle = 0),
          panel.spacing = unit(0.02,'lines'),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank()) +
    xlab("") + ylab("")
}


ps.major <- prune_taxa(taxa_sums(ps) > 100, ps)

plot_heatmap(ps.major, taxa = "Family") + 
  facet_grid(rows = vars(Phylum), 
             cols = vars(Group, BioRepeat), scales = "free", space = "free")
```

## Alpha-diversity

```{r}
# Calculate several alpha-diversity indexes, return one dataframe
alpha_div_table <- function(ps, metric, cols_to_keep){
  require(phyloseq)
  
  ps <- prune_taxa(taxa_sums(ps) > 0, ps)
  ps <- rarefy_even_depth(ps)
  obs_sim <- estimate_richness(ps, split = TRUE, measures = metric)
  alpha <- cbind(sample_data(ps)[,cols_to_keep], obs_sim)
  alpha %>% 
    pivot_longer(all_of(metric), names_to = "Metric")
}


sample_sums(ps) %>% sort()
ps.raref <- rarefy_even_depth(ps)
alpha <- alpha_div_table(ps.raref, 
                         metric = c("Observed", "Simpson"),
                         cols_to_keep = c("Group", "BioRepeat"))
alpha

ggplot(alpha, aes(Group, value)) +
  geom_point(aes(color = BioRepeat)) +
  facet_wrap(~Metric, scales = "free_y")+
  theme_light() +
  xlab("") + ylab("")
```

## Beta-diversity

```{r}
# Plot beta-diversity
beta_plot <- function(ps, method, distance, ...){
  require(phyloseq)
  require(ggplot2)
  
  ps.prop <- transform_sample_counts(ps, function(x) x/sum(x))
  ords <- ordinate(ps.prop, method=method, distance=distance)
  plot_ordination(ps.prop, ords, title=deparse(substitute(ps)), ...) +
    geom_point(size=3, alpha=0.7) + 
    theme_light() +
    ggtitle(distance)
}

beta_plot(ps,
          method = "PCoA", distance = "bray", 
          color="Group", shape = "BioRepeat")
```

## Ideas to check

1.
2.
3.