---
title: "Base R template for 16s amplicon processing"
output: 
  html_document: 
    keep_md: yes
    toc: yes
    toc_float: yes
    toc_collapsed: yes
---

## Intro

This pipeline offers an attempt to standardize procedure of soil 16S and ITS rDNA Illumina reads processing in ARRIAM. Most operations are performed by R libraries and are covered in functions. Here we talk about the most common way of the analysis - for the tuning or for more details you have to manipulate with the functions themselves, in [functions.R](/functions.R) or use them for the building of your own pipeline. 

Required libraries:

* [dada2](https://benjjneb.github.io/dada2/tutorial.html)
* [Biostrings](https://bioconductor.org/packages/release/bioc/html/Biostrings.html)
* [DECIPHER](https://bioconductor.org/packages/release/bioc/html/DECIPHER.html)
* [phyloseq](https://joey711.github.io/phyloseq/)
* [ggplot2](https://ggplot2.tidyverse.org/)
* [ggpubr](https://rpkgs.datanovia.com/ggpubr/)
* [dplyr](https://dplyr.tidyverse.org/)
* [DESeq2](http://bioconductor.org/packages/release/bioc/html/DESeq2.html)


---

## Libraries and functions import

Load required libraries. Please, install them, if you don't have it. Also, import functions, set your working directory and the random seed.

```{r message=FALSE, warning=FALSE}
library(dada2)
library(Biostrings)
library(DECIPHER)
library(phyloseq)
library(tidyverse)


source('functions.R')
set.seed(5678)
```


---

## Dada2 processing of sequences

For processing of data, we need to specify a way to raw data, and file with metadata (information about samples). In our example, raw files are in `/raw` directory, and metadata in `metadata.csv` file of current work directory.

Functions in this module are:

### 16S reads processing

[16S pipeline](16S_pipeline.md)

### ITS reads processing

[ITS pipeline](ITS_pipeline.md)

